Blog App: Feature/validations and specs
Megagig/Blog-App pull request #3
Opened 2023-11-30 20:02 UTC by Megagig

**On this branch:**

 

- [ ] I added the following validations:

- Name must not be blank.
- PostsCounter must be an integer greater than or equal to zero.
- Title must not be blank.
- Title must not exceed 250 characters.
- CommentsCounter must be an integer greater than or equal to zero.
- LikesCounter must be an integer greater than or equal to zero.

- [ ]  I added unit specs for all the models' methods and validations.

2023-11-30 20:34 UTC, KDlamini approved these changes
### Hi @Megagig 🙋‍♀️,  

Great work so far! 💯 
You have done a great job adding model validations and specs. 🎊 🥳 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Well-documented and professional README
✔️  Model validations for User and Post are included
✔️  Specs for model validations are well implemented

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 20:34 UTC, KDlamini commented on spec/models/post_spec.rb
You have done an incredible job testing all the app models. 💯 

As per project requirements, kindly make sure that all public methods are tested.

- **Post Model:** There should be a test the that checks if the `five_most_recent_comments` method returns 5 most recent comments per post.
- **Comment Model:** There should be a test that tests the `update_post_comments_counter` method i.e creating a comment should increment the `CommentsCounter` by one.
- **Like Model:** There should be a test that tests the `update_post_likes_counter` method i.e creating a like should increment the `LikesCounter` by one.

Otherwise, well done with the passing validation specs 🚀 

![image](https://github.com/Megagig/Blog-App/assets/38088818/2083802d-c2bb-431d-b5c5-f7f338f3959b)

2023-11-30 21:01 UTC, Megagig commented on spec/models/post_spec.rb
@KDlamini You approved a pull request and at the same time gave required changes without explicit requirements on what and what to change.

From my end, your response says approved these changes so so mins ago.

Please kindly give clear instructions on what and what needed to be changed to avoid landing one into more confusion.

2023-12-01 09:32 UTC, KDlamini commented on spec/models/post_spec.rb
Hi @Megagig my deepest apologies for the late reply. Kindly focus on the template and the inline comment. The template is for required changes.

I apologize for the confusion. I selected the approve option instead of the require changes option. However, your project is not approved officially. This only appears on Github and is not in sync with the Microverse Dashboard. Kindly apply the required changes as instructed in the inline comment.

Thank you for your understanding 🙏🏾

2023-12-01 11:54 UTC, TadesseDev requested changes
### Hi @Megagig 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 11:54 UTC, TadesseDev commented on spec/models/comment_spec.rb
> +end
- [ ] Dear @Megagig, Just as mentioned by the previouse reviewer, here there should be a test that tests the update_post_comments_counter method. Please keep in mind we need to test all customer methods in our model. hence, we need to check creating a comment is incrementing a CommentsCounter by one.

2023-12-01 11:54 UTC, TadesseDev commented on spec/models/like_spec.rb
> +end
- [ ] Also here, Just as mentioned earlier, there should be a test that tests the `update_post_likes_counter` method. Please add these tests.

2023-12-01 18:46 UTC, shahadat3669 approved these changes
Hi @Megagig, 

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ Worked on previous reviewer comments.
✅ Model validations for Like and Comments are included
✅ Descriptive PR Description
✅ Specs for model validations are well implemented

## Optional suggestions
- [ ] [Optional] **Checking Database Migration Error:** As mentioned in the video call, there seems to be a database migration error in your code. While it may be functioning correctly on your computer, it's essential to verify that it works consistently across different computers. Run your code on other machines to ensure compatibility. By confirming that your code runs smoothly on various computers, you'll enhance its reliability and applicability. Keep up the diligence! 🚀🔍
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 18:53 UTC, Megagig commented
@shahadat3669 
Thank you so much for your thorough review. You even had to call me on Zoom to explain the migration errors. I appreciate the thorough review. You are the best reviewer I have come across since my enrollment in Microverse. Thank You so much for your feedback.

2023-12-01 19:23 UTC, merged